### ISSUE TITLE
parallel subprocess deadlock

### ISSUE THREAD

**Issue by EYH0602** [SecurityLab-UCD/function-embedding#7]
when compiling all the code with `parallel_subprocess`, wait for remaining processes to exit (`p.wait()`)may not exit
https://docs.python.org/3/library/subprocess.html#subprocess.Popen.wait 

to reproduce
```sh
source ./scripts/env.sh
python3.8 scripts/build.py -d POJ104 -w CodeXGLUE/Code-Code/Clone-detection-POJ-104/dataset -j 72 -f O
```
@HazyFish @DataCorrupted

**Comment by EYH0602** [comment]
one way is to remove `p.wait()` in `parallel_subprocess` and let `on_exit` decide to wait or kill the process

**Comment by HazyFish** [comment]
I also encountered deadlock before. I solved it by setting stdout and stderr to `subprocess.DEVNULL` or a file instead of a pipe
